[ci] set back priority txns block space back to 0 as default
Some tests in miner_tests.cpp expect the block space dedicated to low
and 0 fee transactions to be 0. This commit fixes the follwoing errors:

../../src/test/miner_tests.cpp:243: error: in "miner_tests/CreateNewBlock_validity": check pblocktemplate->block->vtx[i]->GetHash() != hashFreeTx has failed
../../src/test/miner_tests.cpp:244: error: in "miner_tests/CreateNewBlock_validity": check pblocktemplate->block->vtx[i]->GetHash() != hashLowFeeTx has failed