[ci] convert token_tests.cpp to be height activated
Before this commit this unit have 8 failures out of 20 tests.
After the conversion the failures have been reduced to 2.

These are the remaining failures:

../../src/test/token_tests.cpp:1722: error: in "token_tests/sighash_utxos_test": check chainActive.Tip()->GetBlockHash() != block.GetHash() has failed
../../src/test/token_tests.cpp:1723: error: in "token_tests/sighash_utxos_test": check pcoinsTip->GetBestBlock() != block.GetHash() has failed

I added 2 debug messages to the failing code, you need to run the unit
test file with `--log_level=all` to see the debug output, namely:

src/test/test_bitcoin  --log_level=all --run_test=token_tests